Rauf-Final/Rauf-Final/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Rauf_Final.Models
{
    public class Project
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(500)]
        public string HeadTitle { get; set; }
        [MaxLength(200)]
        public string LeftTitle { get; set; }
        public DateTime CreatedDate { get; set; }
        [MaxLength(150)]
        public string ClientFullName { get; set; }
        public string RightContent { get; set; }
        [MaxLength(500)]
        public string GoToLink { get; set; }
        [MaxLength(150)]
        public string CategoryTitle { get; set; }
        [MaxLength(2500)]
        public string CategoryContent { get; set; }
        [MaxLength(1000)]
        public string Award { get; set; }
        [ForeignKey("ProjectCategory")]
        public int ProjectCategoryId { get; set; }
        public ProjectCategory ProjectCategory { get; set; }
        [ForeignKey("ProjectPhoto")]
        public int ProjectPhotoId { get; set; }
        public ProjectPhoto ProjectPhoto { get; set; }




    }
}

Rauf-Final/Rauf-Final/Areas/Admin/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rauf_Final.Areas.Admin.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Rauf-Final/Rauf-Final/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rauf_Final.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ProjectDetail()
        {
            return View();
        }
    }
}

Rauf-Final/Rauf-Final/Views/Project/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<!-- Page Title Section -->
<div class="page-title-section">
    <div class="auto-container">
        <ul class="post-meta">
            <li><a href="index.html">Index</a></li>
            <li>Project</li>
        </ul>
        <h2><span>Latest</span> From Our Project</h2>
    </div>
</div>
<!-- End Page Title Section -->
<!-- Project Section -->
<div class="project-section section-padding">
    <div class="outer-container">
        <div class="row clearfix">

            <!-- Column -->
            <div class="column col-lg-6 col-md-12 col-sm-12">
                <div class="row clearfix">

                    <!-- Inner Column -->
                    <div class="inner-column col-lg-6 col-md-6 col-sm-12">
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <img src="images/gallery/2.jpg" alt="" />
                                    <div class="overlay-box">
                                        <div class="overlay-inner">
                                            <h3><a asp-controller="Project" asp-action="ProjectDetail">WOTa Money Save</a></h3>
                                            <div class="designation">Finance, Consulting</div>
                                            <a href="project-details.html" class="arrow ti-angle-right"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Inner Column -->
                    <div class="inner-column col-lg-6 col-md-6 col-sm-12">
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <img src="images/gallery/3.jpg" alt="" />
                                    <div class="overlay-box">
                                        <div class="overlay-inner">
                                            <h3><a href="project-details.html">WOTa Money Save</a></h3>
                                            <div class="designation">Finance, Consulting</div>
                                            <a href="project-details.html" class="arrow ti-angle-right"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Inner Column -->
                    <div class="inner-column col-lg-12 col-md-12 col-sm-12">
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <img src="images/gallery/4.jpg" alt="" />
                                    <div class="overlay-box">
                                        <div class="overlay-inner">
                                            <h3><a href="project-details.html">WOTa Money Save</a></h3>
                                            <div class="designation">Finance, Consulting</div>
                                            <a href="project-details.html" class="arrow ti-angle-right"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- Column -->
            <div class="column col-lg-6 col-md-12 col-sm-12">
                <div class="gallery-block">
                    <div class="inner-box">
                        <div class="image">
                            <img src="images/gallery/1.jpg" alt="" />
                            <div class="overlay-box">
                                <div class="overlay-inner">
                                    <h3><a href="project-details.html">WOTa Money Save</a></h3>
                                    <div class="designation">Finance, Consulting</div>
                                    <a href="project-details.html" class="arrow ti-angle-right"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- End Project Section -->

Rauf-Final/Rauf-Final/Views/Project/ProjectDetail.cshtml
@{
    ViewData["Title"] = "ProjectDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Title Section -->
<div class="page-title-section">
    <div class="auto-container">
        <ul class="post-meta">
            <li><a href="index.html">Index</a></li>
            <li>Project</li>
        </ul>
        <h2><span>Latest</span> From Our Project</h2>
    </div>
</div>
<!-- End Page Title Section -->

<div class="project-section section-padding">
    <div class="auto-container">
        <div class="row">

            <!-- Portfolio Left -->
            <div class="col-lg-4 col-md-6 col-12">
                <div class="work-left work-details">
                    <div class="portfolio-main-info">
                        <h2 class="title">About the <br> project</h2>
                        <!-- Start Details List -->
                        <div class="work-details-list mt-60">

                            <div class="details-list">
                                <label>Date</label>
                                <span>28 Sep 2007</span>
                            </div>

                            <div class="details-list">
                                <label>Client</label>
                                <span>HighGrove Partners</span>
                            </div>

                            <div class="details-list">
                                <label>Categories</label>
                                <span><a href="#">Digital</a></span>
                            </div>

                            <div class="details-list">
                                <label>Awards</label>
                                <span>2015 Digital World Awards 2016 Finale Awards</span>
                            </div>

                        </div>
                        <!-- End Details List -->
                        <!-- Start Work Share -->
                        <div class="work-share section-padding-top-70">
                            <h6 class="heading heading-h6">SHARE</h6>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Work Right -->
            <div class="col-lg-7 col-md-6 offset-lg-1 col-12">
                <div class="work-left work-details mt-lg-30">
                    <div class="work-main-info">
                        <div class="work-content">
                            <h6 class="title">ABOUT THE PROJECT</h6>

                            <div class="desc mt-40">
                                <div class="content mb-25">
                                    <p>
                                        Digital marketing encompasses all marketing efforts
                                        that use an electronic device or the internet. Businesses leverage
                                        digital channels such as search engines, social media, email, and
                                        their websites to connect with current and prospective customers.
                                    </p>
                                </div>
                                <div class="content mb-25">
                                    <p>
                                        It is. In fact, “constant” internet usage among
                                        adults increased by 5% in just the last three years, according to
                                        Pew Research. And although we say it a lot, the way people shop and
                                        buy really has changed along with it — meaning offline marketing
                                        isn’t as effective as it used to be.
                                    </p>
                                </div>
                                <div class="content mb-60">
                                    <p>
                                        Marketing has always been about connecting with your
                                        audience in the right place and at the right time. Today, that
                                        means you need to meet them where they are already spending time:
                                        on the internet. (Source: blog.hubspot.com)
                                    </p>
                                </div>

                                <div class="work-btn">
                                    <a class="theme-btn btn-style-one" href="#"><span class="txt">Go to link</span></a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Start Thumbnail -->
        <div class="row">
            <div class="col-lg-12">
                <div class="custom-column-thumbnail mt-lg-70">
                    <img class="w-100" src="~/images/project/project-1.jpg" alt="finance">
                </div>
            </div>
        </div>

        <!-- Start Digital Marketion Area -->
        <div class="row mt-lg-100">
            <div class="col-lg-4 col-md-12 col-12">
                <div class="digital-marketing">
                    <h3 class="heading heading-h3">Digital Marketing.</h3>
                </div>
            </div>
            <div class="col-lg-7 col-md-12 col-12 offset-lg-1">
                <div class="digital-marketing mt-30">
                    <div class="inner">
                        <p>
                            Marketing has always been about connecting with your audience in
                            the right place and at the right time. Today, that means you need to meet them
                            where they are already spending time: on the internet. A seasoned inbound
                            marketer might say inbound marketing and digital marketing are virtually the
                            same thing, but there are some minor differences. And conversations with
                            marketers and business owners in the U.S., U.K., Asia, Australia, and New
                            Zealand, I've learned a lot about how those small differences are being
                            observed across the world.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Digital Marketion Area -->
        <!-- Start Gallery Area -->
        <div class="custom-layout-gallery mt-lg-100">
            <div class="row mb-n30">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="thumbnail">
                        <img class="w-100" src="~/images/project/project-3.jpg" alt="finance">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12 mt-50">
                    <div class="thumbnail">
                        <img class="w-100" src="~/images/project/project-4.jpg" alt="finance">
                    </div>
                </div>

                <div class="col-lg-12 mtb-30">
                    <div class="thumbnail">
                        <img class="w-100" src="~/images/project/project-2.jpg" alt="finance">
                    </div>
                </div>
            </div>
        </div>
        <!-- End Gallery Area -->


    </div>
</div>